export const Constants = {
  NOTION_API_KEY: process.env.NOTION_API_KEY,
  MEDIUM_COOKIE_SID: process.env.MEDIUM_COOKIE_SID,
  MEDIUM_COOKIE_UID: process.env.MEDIUM_COOKIE_UID,
  NOTION_SUBMISSION_DATABASE_ID: process.env.NOTION_SUBMISSION_DATABASE_ID,
}
